apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: italogfx/auth-service:v2
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              value: mysql://root:1234@mysql:3306/school

